import React from "react";
import { useEffect } from "react";
import { useState } from "react";
import Card from "./Card";

const Random = () => {
  const [input, setInput] = useState([  
{
  "idMeal": "52771",
  "strMeal": "Spicy Arrabiata Penne",
  "strDrinkAlternate": null,
  "strCategory": "Vegetarian",
  "strArea": "Italian",
  "strInstructions": "Bring a large pot of water to a boil. Add kosher salt to the boiling water, then add the pasta. Cook according to the package instructions, about 9 minutes.\r\nIn a large skillet over medium-high heat, add the olive oil and heat until the oil starts to shimmer. Add the garlic and cook, stirring, until fragrant, 1 to 2 minutes. Add the chopped tomatoes, red chile flakes, Italian seasoning and salt and pepper to taste. Bring to a boil and cook for 5 minutes. Remove from the heat and add the chopped basil.\r\nDrain the pasta and add it to the sauce. Garnish with Parmigiano-Reggiano flakes and more basil and serve warm.",
  "strMealThumb": "https://www.themealdb.com/images/media/meals/ustsqw1468250014.jpg",
  "strTags": "Pasta,Curry",
  "strYoutube": "https://www.youtube.com/watch?v=1IszT_guI08",
  "strIngredient1": "penne rigate",
  "strIngredient2": "olive oil",
  "strIngredient3": "garlic",
  "strIngredient4": "chopped tomatoes",
  "strIngredient5": "red chile flakes",
  "strIngredient6": "italian seasoning",
  "strIngredient7": "basil",
  "strIngredient8": "Parmigiano-Reggiano",
  "strIngredient9": "",
  "strIngredient10": "",
  "strIngredient11": "",
  "strIngredient12": "",
  "strIngredient13": "",
  "strIngredient14": "",
  "strIngredient15": "",
  "strIngredient16": null,
  "strIngredient17": null,
  "strIngredient18": null,
  "strIngredient19": null,
  "strIngredient20": null,
  "strMeasure1": "1 pound",
  "strMeasure2": "1/4 cup",
  "strMeasure3": "3 cloves",
  "strMeasure4": "1 tin ",
  "strMeasure5": "1/2 teaspoon",
  "strMeasure6": "1/2 teaspoon",
  "strMeasure7": "6 leaves",
  "strMeasure8": "spinkling",
  "strMeasure9": "",
  "strMeasure10": "",
  "strMeasure11": "",
  "strMeasure12": "",
  "strMeasure13": "",
  "strMeasure14": "",
  "strMeasure15": "",
  "strMeasure16": null,
  "strMeasure17": null,
  "strMeasure18": null,
  "strMeasure19": null,
  "strMeasure20": null,
  "strSource": null,
  "strImageSource": null,
  "strCreativeCommonsConfirmed": null,
  "dateModified": null
  },
  
{
  "idMeal": "52848",
  "strMeal": "Bean & Sausage Hotpot",
  "strDrinkAlternate": null,
  "strCategory": "Miscellaneous",
  "strArea": "British",
  "strInstructions": "In a large casserole, fry the sausages until brown all over – about 10 mins.\r\n\r\nAdd the tomato sauce, stirring well, then stir in the beans, treacle or sugar and mustard. Bring to the simmer, cover and cook for 30 mins. Great served with crusty bread or rice.",
  "strMealThumb": "https://www.themealdb.com/images/media/meals/vxuyrx1511302687.jpg",
  "strTags": null,
  "strYoutube": "https://www.youtube.com/watch?v=B0YX0yPX4Wo",
  "strIngredient1": "Sausages",
  "strIngredient2": "Tomato Sauce",
  "strIngredient3": "Butter Beans",
  "strIngredient4": "Black Treacle",
  "strIngredient5": "English Mustard",
  "strIngredient6": "",
  "strIngredient7": "",
  "strIngredient8": "",
  "strIngredient9": "",
  "strIngredient10": "",
  "strIngredient11": "",
  "strIngredient12": "",
  "strIngredient13": "",
  "strIngredient14": "",
  "strIngredient15": "",
  "strIngredient16": "",
  "strIngredient17": "",
  "strIngredient18": "",
  "strIngredient19": "",
  "strIngredient20": "",
  "strMeasure1": "8 large",
  "strMeasure2": "1 Jar",
  "strMeasure3": "1200g",
  "strMeasure4": "1 tbls",
  "strMeasure5": "1 tsp ",
  "strMeasure6": "",
  "strMeasure7": "",
  "strMeasure8": "",
  "strMeasure9": "",
  "strMeasure10": "",
  "strMeasure11": "",
  "strMeasure12": "",
  "strMeasure13": "",
  "strMeasure14": "",
  "strMeasure15": "",
  "strMeasure16": "",
  "strMeasure17": "",
  "strMeasure18": "",
  "strMeasure19": "",
  "strMeasure20": "",
  "strSource": "https://www.bbcgoodfood.com/recipes/339607/bean-and-sausage-hotpot",
  "strImageSource": null,
  "strCreativeCommonsConfirmed": null,
  "dateModified": null
  },

  {
    "idMeal": "52794",
    "strMeal": "Vegan Chocolate Cake",
    "strDrinkAlternate": null,
    "strCategory": "Vegan",
    "strArea": "American",
    "strInstructions": "Simply mix all dry ingredients with wet ingredients and blend altogether. Bake for 45 min on 180 degrees. Decorate with some melted vegan chocolate ",
    "strMealThumb": "https://www.themealdb.com/images/media/meals/qxutws1486978099.jpg",
    "strTags": "Vegan,Chocolate,Cake",
    "strYoutube": "https://www.youtube.com/watch?v=C3pAgB7pync",
    "strIngredient1": "self raising flour",
    "strIngredient2": "coco sugar",
    "strIngredient3": "cacao",
    "strIngredient4": "baking powder",
    "strIngredient5": "flax eggs",
    "strIngredient6": "almond milk",
    "strIngredient7": "vanilla",
    "strIngredient8": "water",
    "strIngredient9": "",
    "strIngredient10": "",
    "strIngredient11": "",
    "strIngredient12": "",
    "strIngredient13": "",
    "strIngredient14": "",
    "strIngredient15": "",
    "strIngredient16": "",
    "strIngredient17": "",
    "strIngredient18": "",
    "strIngredient19": "",
    "strIngredient20": "",
    "strMeasure1": "1 1/4 cup",
    "strMeasure2": "1/2 cup",
    "strMeasure3": "1/3 cup raw",
    "strMeasure4": "1 tsp",
    "strMeasure5": "2",
    "strMeasure6": "1/2 cup",
    "strMeasure7": "1 tsp",
    "strMeasure8": "1/2 cup boiling",
    "strMeasure9": "",
    "strMeasure10": "",
    "strMeasure11": "",
    "strMeasure12": "",
    "strMeasure13": "",
    "strMeasure14": "",
    "strMeasure15": "",
    "strMeasure16": "",
    "strMeasure17": "",
    "strMeasure18": "",
    "strMeasure19": "",
    "strMeasure20": "",
    "strSource": "",
    "strImageSource": null,
    "strCreativeCommonsConfirmed": null,
    "dateModified": null
    }
  ]);
  
  return (
    <div className="container mx-auto flex flex-wrap gap-10 justify-center align-center py-4 bg-base-200">
      {input?.map((product) => {
        return (
          <Card
            key={product.idMeal}
            product={product}
            name={product.strMeal}
            id={product.idMeal}
          />
        );
      })}
    </div>
  );
};

export default Random;
